var namespacetaraxa_1_1state__api =
[
    [ "Account", "group___final_chain.html#structtaraxa_1_1state__api_1_1_account", "group___final_chain_structtaraxa_1_1state__api_1_1_account" ],
    [ "BlockRewardsOptions", "namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_block_rewards_options", "namespacetaraxa_1_1state__api_structtaraxa_1_1state__api_1_1_block_rewards_options_dup" ],
    [ "Config", "namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_config", "namespacetaraxa_1_1state__api_structtaraxa_1_1state__api_1_1_config_dup" ],
    [ "DPOSConfig", "namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_d_p_o_s_config", "namespacetaraxa_1_1state__api_structtaraxa_1_1state__api_1_1_d_p_o_s_config_dup" ],
    [ "ErrFutureBlock", "group___final_chain.html#structtaraxa_1_1state__api_1_1_err_future_block", "group___final_chain_structtaraxa_1_1state__api_1_1_err_future_block" ],
    [ "ErrorHandler", "classtaraxa_1_1state__api_1_1_error_handler.html", "classtaraxa_1_1state__api_1_1_error_handler" ],
    [ "ETHChainConfig", "namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_e_t_h_chain_config", "namespacetaraxa_1_1state__api_structtaraxa_1_1state__api_1_1_e_t_h_chain_config_dup" ],
    [ "EVMBlock", "group___final_chain.html#structtaraxa_1_1state__api_1_1_e_v_m_block", "group___final_chain_structtaraxa_1_1state__api_1_1_e_v_m_block" ],
    [ "EVMTransaction", "group___final_chain.html#structtaraxa_1_1state__api_1_1_e_v_m_transaction", "group___final_chain_structtaraxa_1_1state__api_1_1_e_v_m_transaction" ],
    [ "ExecutionOptions", "namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_execution_options", "namespacetaraxa_1_1state__api_structtaraxa_1_1state__api_1_1_execution_options_dup" ],
    [ "ExecutionResult", "group___final_chain.html#structtaraxa_1_1state__api_1_1_execution_result", "group___final_chain_structtaraxa_1_1state__api_1_1_execution_result" ],
    [ "LogRecord", "group___final_chain.html#structtaraxa_1_1state__api_1_1_log_record", "group___final_chain_structtaraxa_1_1state__api_1_1_log_record" ],
    [ "Opts", "namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_opts", "namespacetaraxa_1_1state__api_structtaraxa_1_1state__api_1_1_opts_dup" ],
    [ "OptsDB", "namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_opts_d_b", "namespacetaraxa_1_1state__api_structtaraxa_1_1state__api_1_1_opts_d_b_dup" ],
    [ "Proof", "group___final_chain.html#structtaraxa_1_1state__api_1_1_proof", "group___final_chain_structtaraxa_1_1state__api_1_1_proof" ],
    [ "StateAPI", "group___final_chain.html#classtaraxa_1_1state__api_1_1_state_a_p_i", "group___final_chain_classtaraxa_1_1state__api_1_1_state_a_p_i" ],
    [ "StateDescriptor", "group___final_chain.html#structtaraxa_1_1state__api_1_1_state_descriptor", "group___final_chain_structtaraxa_1_1state__api_1_1_state_descriptor" ],
    [ "StateTransitionResult", "group___final_chain.html#structtaraxa_1_1state__api_1_1_state_transition_result", "group___final_chain_structtaraxa_1_1state__api_1_1_state_transition_result" ],
    [ "TaraxaEVMError", "group___final_chain.html#structtaraxa_1_1state__api_1_1_taraxa_e_v_m_error", "group___final_chain_structtaraxa_1_1state__api_1_1_taraxa_e_v_m_error" ],
    [ "TrieProof", "group___final_chain.html#structtaraxa_1_1state__api_1_1_trie_proof", "group___final_chain_structtaraxa_1_1state__api_1_1_trie_proof" ],
    [ "UncleBlock", "group___final_chain.html#structtaraxa_1_1state__api_1_1_uncle_block", "group___final_chain_structtaraxa_1_1state__api_1_1_uncle_block" ],
    [ "ValidatorInfo", "namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_validator_info", "namespacetaraxa_1_1state__api_structtaraxa_1_1state__api_1_1_validator_info_dup" ]
];