var searchData=
[
  ['validatorinfo_4387',['ValidatorInfo',['../namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_validator_info',1,'taraxa::state_api']]],
  ['validatorstake_4388',['ValidatorStake',['../group___final_chain.html#structtaraxa_1_1state__api_1_1_validator_stake',1,'taraxa::state_api']]],
  ['validatorstats_4389',['ValidatorStats',['../classtaraxa_1_1rewards_1_1_block_stats.html#structtaraxa_1_1rewards_1_1_block_stats_1_1_validator_stats',1,'taraxa::rewards::BlockStats']]],
  ['validatorvotecount_4390',['ValidatorVoteCount',['../group___final_chain.html#structtaraxa_1_1state__api_1_1_validator_vote_count',1,'taraxa::state_api']]],
  ['validatorvotecountchange_4391',['ValidatorVoteCountChange',['../structtaraxa_1_1pillar__chain_1_1_pillar_block_1_1_validator_vote_count_change.html',1,'taraxa::pillar_chain::PillarBlock']]],
  ['valuebyblockcache_4392',['ValueByBlockCache',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20const_20sharedtransactions_20_3e_4393',['ValueByBlockCache&lt; const SharedTransactions &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3aoptional_3c_20const_20dev_3a_3afixedhash_20_3e_20_3e_4394',['ValueByBlockCache&lt; std::optional&lt; const dev::FixedHash &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3ashared_5fptr_3c_20const_20taraxa_3a_3afinal_5fchain_3a_3ablockheader_20_3e_20_3e_4395',['ValueByBlockCache&lt; std::shared_ptr&lt; const taraxa::final_chain::BlockHeader &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3ashared_5fptr_3c_20const_20transactionhashes_20_3e_20_3e_4396',['ValueByBlockCache&lt; std::shared_ptr&lt; const TransactionHashes &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20uint64_5ft_20_3e_4397',['ValueByBlockCache&lt; uint64_t &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['vdfparams_4398',['VdfParams',['../namespacetaraxa.html#structtaraxa_1_1_vdf_params',1,'taraxa']]],
  ['vdfsortition_4399',['VdfSortition',['../classtaraxa_1_1vdf__sortition_1_1_vdf_sortition.html',1,'taraxa::vdf_sortition']]],
  ['vector_5fref_4400',['vector_ref',['../classdev_1_1vector__ref.html',1,'dev']]],
  ['vector_5fref_3c_3a_3abyte_20const_20_3e_4401',['vector_ref&lt;::byte const &gt;',['../classdev_1_1vector__ref.html',1,'dev']]],
  ['verifiedvotes_4402',['VerifiedVotes',['../namespacetaraxa.html#structtaraxa_1_1_verified_votes',1,'taraxa']]],
  ['vertex_5flabel_5fwriter_4403',['vertex_label_writer',['../group___d_a_g.html#classtaraxa_1_1vertex__label__writer',1,'taraxa']]],
  ['vote_4404',['Vote',['../group___vote.html#classtaraxa_1_1_vote',1,'taraxa']]],
  ['votemanager_4405',['VoteManager',['../group___vote.html#classtaraxa_1_1_vote_manager',1,'taraxa']]],
  ['votepacket_4406',['VotePacket',['../namespacetaraxa_1_1network_1_1tarcap.html#structtaraxa_1_1network_1_1tarcap_1_1_vote_packet',1,'taraxa::network::tarcap']]],
  ['votepackethandler_4407',['VotePacketHandler',['../classtaraxa_1_1network_1_1tarcap_1_1v4_1_1_vote_packet_handler.html',1,'taraxa::network::tarcap::v4::VotePacketHandler'],['../classtaraxa_1_1network_1_1tarcap_1_1_vote_packet_handler.html',1,'taraxa::network::tarcap::VotePacketHandler']]],
  ['votesbundlepacket_4408',['VotesBundlePacket',['../namespacetaraxa_1_1network_1_1tarcap.html#structtaraxa_1_1network_1_1tarcap_1_1_votes_bundle_packet',1,'taraxa::network::tarcap']]],
  ['votesbundlepackethandler_4409',['VotesBundlePacketHandler',['../classtaraxa_1_1network_1_1tarcap_1_1v4_1_1_votes_bundle_packet_handler.html',1,'taraxa::network::tarcap::v4::VotesBundlePacketHandler'],['../classtaraxa_1_1network_1_1tarcap_1_1_votes_bundle_packet_handler.html',1,'taraxa::network::tarcap::VotesBundlePacketHandler']]],
  ['vrfparams_4410',['VrfParams',['../structtaraxa_1_1_vrf_params.html',1,'taraxa']]],
  ['vrfpbftmsg_4411',['VrfPbftMsg',['../group___vote.html#classtaraxa_1_1_vrf_pbft_msg',1,'taraxa']]],
  ['vrfpbftsortition_4412',['VrfPbftSortition',['../group___vote.html#classtaraxa_1_1_vrf_pbft_sortition',1,'taraxa']]],
  ['vrfsortitionbase_4413',['VrfSortitionBase',['../classtaraxa_1_1vrf__wrapper_1_1_vrf_sortition_base.html',1,'taraxa::vrf_wrapper']]]
];
