var searchData=
[
  ['validatorinfo_4396',['ValidatorInfo',['../namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_validator_info',1,'taraxa::state_api']]],
  ['validatorstake_4397',['ValidatorStake',['../group___final_chain.html#structtaraxa_1_1state__api_1_1_validator_stake',1,'taraxa::state_api']]],
  ['validatorstats_4398',['ValidatorStats',['../classtaraxa_1_1rewards_1_1_block_stats.html#structtaraxa_1_1rewards_1_1_block_stats_1_1_validator_stats',1,'taraxa::rewards::BlockStats']]],
  ['validatorvotecount_4399',['ValidatorVoteCount',['../group___final_chain.html#structtaraxa_1_1state__api_1_1_validator_vote_count',1,'taraxa::state_api']]],
  ['validatorvotecountchange_4400',['ValidatorVoteCountChange',['../structtaraxa_1_1pillar__chain_1_1_pillar_block_1_1_validator_vote_count_change.html',1,'taraxa::pillar_chain::PillarBlock']]],
  ['valuebyblockcache_4401',['ValueByBlockCache',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20const_20sharedtransactions_20_3e_4402',['ValueByBlockCache&lt; const SharedTransactions &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3aoptional_3c_20const_20dev_3a_3afixedhash_20_3e_20_3e_4403',['ValueByBlockCache&lt; std::optional&lt; const dev::FixedHash &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3ashared_5fptr_3c_20const_20taraxa_3a_3afinal_5fchain_3a_3ablockheader_20_3e_20_3e_4404',['ValueByBlockCache&lt; std::shared_ptr&lt; const taraxa::final_chain::BlockHeader &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3ashared_5fptr_3c_20const_20transactionhashes_20_3e_20_3e_4405',['ValueByBlockCache&lt; std::shared_ptr&lt; const TransactionHashes &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20uint64_5ft_20_3e_4406',['ValueByBlockCache&lt; uint64_t &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['vdfparams_4407',['VdfParams',['../namespacetaraxa.html#structtaraxa_1_1_vdf_params',1,'taraxa']]],
  ['vdfsortition_4408',['VdfSortition',['../classtaraxa_1_1vdf__sortition_1_1_vdf_sortition.html',1,'taraxa::vdf_sortition']]],
  ['vector_5fref_4409',['vector_ref',['../classdev_1_1vector__ref.html',1,'dev']]],
  ['vector_5fref_3c_3a_3abyte_20const_20_3e_4410',['vector_ref&lt;::byte const &gt;',['../classdev_1_1vector__ref.html',1,'dev']]],
  ['verifiedvotes_4411',['VerifiedVotes',['../namespacetaraxa.html#structtaraxa_1_1_verified_votes',1,'taraxa']]],
  ['vertex_5flabel_5fwriter_4412',['vertex_label_writer',['../group___d_a_g.html#classtaraxa_1_1vertex__label__writer',1,'taraxa']]],
  ['vote_4413',['Vote',['../group___vote.html#classtaraxa_1_1_vote',1,'taraxa']]],
  ['votemanager_4414',['VoteManager',['../group___vote.html#classtaraxa_1_1_vote_manager',1,'taraxa']]],
  ['votepacket_4415',['VotePacket',['../namespacetaraxa_1_1network_1_1tarcap.html#structtaraxa_1_1network_1_1tarcap_1_1_vote_packet',1,'taraxa::network::tarcap']]],
  ['votepackethandler_4416',['VotePacketHandler',['../classtaraxa_1_1network_1_1tarcap_1_1v4_1_1_vote_packet_handler.html',1,'taraxa::network::tarcap::v4::VotePacketHandler'],['../classtaraxa_1_1network_1_1tarcap_1_1_vote_packet_handler.html',1,'taraxa::network::tarcap::VotePacketHandler']]],
  ['votesbundlepacket_4417',['VotesBundlePacket',['../namespacetaraxa_1_1network_1_1tarcap.html#structtaraxa_1_1network_1_1tarcap_1_1_votes_bundle_packet',1,'taraxa::network::tarcap']]],
  ['votesbundlepackethandler_4418',['VotesBundlePacketHandler',['../classtaraxa_1_1network_1_1tarcap_1_1v4_1_1_votes_bundle_packet_handler.html',1,'taraxa::network::tarcap::v4::VotesBundlePacketHandler'],['../classtaraxa_1_1network_1_1tarcap_1_1_votes_bundle_packet_handler.html',1,'taraxa::network::tarcap::VotesBundlePacketHandler']]],
  ['vrfparams_4419',['VrfParams',['../structtaraxa_1_1_vrf_params.html',1,'taraxa']]],
  ['vrfpbftmsg_4420',['VrfPbftMsg',['../group___vote.html#classtaraxa_1_1_vrf_pbft_msg',1,'taraxa']]],
  ['vrfpbftsortition_4421',['VrfPbftSortition',['../group___vote.html#classtaraxa_1_1_vrf_pbft_sortition',1,'taraxa']]],
  ['vrfsortitionbase_4422',['VrfSortitionBase',['../classtaraxa_1_1vrf__wrapper_1_1_vrf_sortition_base.html',1,'taraxa::vrf_wrapper']]]
];
