var searchData=
[
  ['validatorinfo_3802',['ValidatorInfo',['../namespacetaraxa_1_1state__api.html#structtaraxa_1_1state__api_1_1_validator_info',1,'taraxa::state_api']]],
  ['validatorstats_3803',['ValidatorStats',['../classtaraxa_1_1_rewards_stats.html#structtaraxa_1_1_rewards_stats_1_1_validator_stats',1,'taraxa::RewardsStats']]],
  ['valuebyblockcache_3804',['ValueByBlockCache',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20const_20sharedtransactions_20_3e_3805',['ValueByBlockCache&lt; const SharedTransactions &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3aoptional_3c_20const_20dev_3a_3afixedhash_20_3e_20_3e_3806',['ValueByBlockCache&lt; std::optional&lt; const dev::FixedHash &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3ashared_5fptr_3c_20const_20taraxa_3a_3afinal_5fchain_3a_3ablockheader_20_3e_20_3e_3807',['ValueByBlockCache&lt; std::shared_ptr&lt; const taraxa::final_chain::BlockHeader &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20std_3a_3ashared_5fptr_3c_20const_20transactionhashes_20_3e_20_3e_3808',['ValueByBlockCache&lt; std::shared_ptr&lt; const TransactionHashes &gt; &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['valuebyblockcache_3c_20uint64_5ft_20_3e_3809',['ValueByBlockCache&lt; uint64_t &gt;',['../classtaraxa_1_1_value_by_block_cache.html',1,'taraxa']]],
  ['vdfparams_3810',['VdfParams',['../namespacetaraxa.html#structtaraxa_1_1_vdf_params',1,'taraxa']]],
  ['vdfsortition_3811',['VdfSortition',['../classtaraxa_1_1vdf__sortition_1_1_vdf_sortition.html',1,'taraxa::vdf_sortition']]],
  ['vector_5fref_3812',['vector_ref',['../classdev_1_1vector__ref.html',1,'dev']]],
  ['vector_5fref_3c_3a_3abyte_20const_20_3e_3813',['vector_ref&lt;::byte const &gt;',['../classdev_1_1vector__ref.html',1,'dev']]],
  ['vertex_5flabel_5fwriter_3814',['vertex_label_writer',['../group___d_a_g.html#classtaraxa_1_1vertex__label__writer',1,'taraxa']]],
  ['vote_3815',['Vote',['../group___vote.html#classtaraxa_1_1_vote',1,'taraxa']]],
  ['votemanager_3816',['VoteManager',['../group___vote.html#classtaraxa_1_1_vote_manager',1,'taraxa']]],
  ['votepackethandler_3817',['VotePacketHandler',['../classtaraxa_1_1network_1_1tarcap_1_1_vote_packet_handler.html',1,'taraxa::network::tarcap']]],
  ['votesbundle_3818',['VotesBundle',['../group___vote.html#structtaraxa_1_1_votes_bundle',1,'taraxa']]],
  ['votessyncpackethandler_3819',['VotesSyncPacketHandler',['../classtaraxa_1_1network_1_1tarcap_1_1_votes_sync_packet_handler.html',1,'taraxa::network::tarcap']]],
  ['vrfparams_3820',['VrfParams',['../structtaraxa_1_1_vrf_params.html',1,'taraxa']]],
  ['vrfpbftmsg_3821',['VrfPbftMsg',['../group___vote.html#structtaraxa_1_1_vrf_pbft_msg',1,'taraxa']]],
  ['vrfpbftsortition_3822',['VrfPbftSortition',['../group___vote.html#classtaraxa_1_1_vrf_pbft_sortition',1,'taraxa']]],
  ['vrfsortitionbase_3823',['VrfSortitionBase',['../classtaraxa_1_1vrf__wrapper_1_1_vrf_sortition_base.html',1,'taraxa::vrf_wrapper']]]
];
