// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/backend.proto

#include "google/api/backend.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fapi_2fbackend_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fapi_2fbackend_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BackendRule;
}  // namespace protobuf_google_2fapi_2fbackend_2eproto
namespace google {
namespace api {
class BackendDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Backend>
      _instance;
} _Backend_default_instance_;
class BackendRuleDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BackendRule>
      _instance;
  ::google::protobuf::internal::ArenaStringPtr jwt_audience_;
} _BackendRule_default_instance_;
}  // namespace api
}  // namespace google
namespace protobuf_google_2fapi_2fbackend_2eproto {
static void InitDefaultsBackend() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::api::_Backend_default_instance_;
    new (ptr) ::google::api::Backend();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::api::Backend::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Backend =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsBackend}, {
      &protobuf_google_2fapi_2fbackend_2eproto::scc_info_BackendRule.base,}};

static void InitDefaultsBackendRule() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::api::_BackendRule_default_instance_;
    new (ptr) ::google::api::BackendRule();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::api::BackendRule::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BackendRule =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBackendRule}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Backend.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BackendRule.base);
}

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::Backend, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::Backend, rules_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, selector_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, address_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, deadline_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, min_deadline_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, operation_deadline_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, path_translation_),
  offsetof(::google::api::BackendRuleDefaultTypeInternal, jwt_audience_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::BackendRule, authentication_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::google::api::Backend)},
  { 6, -1, sizeof(::google::api::BackendRule)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::api::_Backend_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::api::_BackendRule_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "google/api/backend.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030google/api/backend.proto\022\ngoogle.api\"1"
      "\n\007Backend\022&\n\005rules\030\001 \003(\0132\027.google.api.Ba"
      "ckendRule\"\310\002\n\013BackendRule\022\020\n\010selector\030\001 "
      "\001(\t\022\017\n\007address\030\002 \001(\t\022\020\n\010deadline\030\003 \001(\001\022\024"
      "\n\014min_deadline\030\004 \001(\001\022\032\n\022operation_deadli"
      "ne\030\005 \001(\001\022A\n\020path_translation\030\006 \001(\0162\'.goo"
      "gle.api.BackendRule.PathTranslation\022\026\n\014j"
      "wt_audience\030\007 \001(\tH\000\"e\n\017PathTranslation\022 "
      "\n\034PATH_TRANSLATION_UNSPECIFIED\020\000\022\024\n\020CONS"
      "TANT_ADDRESS\020\001\022\032\n\026APPEND_PATH_TO_ADDRESS"
      "\020\002B\020\n\016authenticationBn\n\016com.google.apiB\014"
      "BackendProtoP\001ZEgoogle.golang.org/genpro"
      "to/googleapis/api/serviceconfig;servicec"
      "onfig\242\002\004GAPIb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 540);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "google/api/backend.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_google_2fapi_2fbackend_2eproto
namespace google {
namespace api {
const ::google::protobuf::EnumDescriptor* BackendRule_PathTranslation_descriptor() {
  protobuf_google_2fapi_2fbackend_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_google_2fapi_2fbackend_2eproto::file_level_enum_descriptors[0];
}
bool BackendRule_PathTranslation_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const BackendRule_PathTranslation BackendRule::PATH_TRANSLATION_UNSPECIFIED;
const BackendRule_PathTranslation BackendRule::CONSTANT_ADDRESS;
const BackendRule_PathTranslation BackendRule::APPEND_PATH_TO_ADDRESS;
const BackendRule_PathTranslation BackendRule::PathTranslation_MIN;
const BackendRule_PathTranslation BackendRule::PathTranslation_MAX;
const int BackendRule::PathTranslation_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void Backend::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Backend::kRulesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Backend::Backend()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fapi_2fbackend_2eproto::scc_info_Backend.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.Backend)
}
Backend::Backend(const Backend& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      rules_(from.rules_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.api.Backend)
}

void Backend::SharedCtor() {
}

Backend::~Backend() {
  // @@protoc_insertion_point(destructor:google.api.Backend)
  SharedDtor();
}

void Backend::SharedDtor() {
}

void Backend::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Backend::descriptor() {
  ::protobuf_google_2fapi_2fbackend_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fbackend_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Backend& Backend::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fbackend_2eproto::scc_info_Backend.base);
  return *internal_default_instance();
}


void Backend::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.Backend)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  rules_.Clear();
  _internal_metadata_.Clear();
}

bool Backend::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.Backend)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .google.api.BackendRule rules = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_rules()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.Backend)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.Backend)
  return false;
#undef DO_
}

void Backend::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.Backend)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .google.api.BackendRule rules = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->rules_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->rules(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.api.Backend)
}

::google::protobuf::uint8* Backend::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.api.Backend)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .google.api.BackendRule rules = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->rules_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->rules(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.Backend)
  return target;
}

size_t Backend::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.Backend)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .google.api.BackendRule rules = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->rules_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->rules(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Backend::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.Backend)
  GOOGLE_DCHECK_NE(&from, this);
  const Backend* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Backend>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.Backend)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.Backend)
    MergeFrom(*source);
  }
}

void Backend::MergeFrom(const Backend& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.Backend)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  rules_.MergeFrom(from.rules_);
}

void Backend::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.Backend)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Backend::CopyFrom(const Backend& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.Backend)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Backend::IsInitialized() const {
  return true;
}

void Backend::Swap(Backend* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Backend::InternalSwap(Backend* other) {
  using std::swap;
  CastToBase(&rules_)->InternalSwap(CastToBase(&other->rules_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Backend::GetMetadata() const {
  protobuf_google_2fapi_2fbackend_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fbackend_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void BackendRule::InitAsDefaultInstance() {
  ::google::api::_BackendRule_default_instance_.jwt_audience_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BackendRule::kSelectorFieldNumber;
const int BackendRule::kAddressFieldNumber;
const int BackendRule::kDeadlineFieldNumber;
const int BackendRule::kMinDeadlineFieldNumber;
const int BackendRule::kOperationDeadlineFieldNumber;
const int BackendRule::kPathTranslationFieldNumber;
const int BackendRule::kJwtAudienceFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BackendRule::BackendRule()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fapi_2fbackend_2eproto::scc_info_BackendRule.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.BackendRule)
}
BackendRule::BackendRule(const BackendRule& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  selector_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.selector().size() > 0) {
    selector_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selector_);
  }
  address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.address().size() > 0) {
    address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.address_);
  }
  ::memcpy(&deadline_, &from.deadline_,
    static_cast<size_t>(reinterpret_cast<char*>(&path_translation_) -
    reinterpret_cast<char*>(&deadline_)) + sizeof(path_translation_));
  clear_has_authentication();
  switch (from.authentication_case()) {
    case kJwtAudience: {
      set_jwt_audience(from.jwt_audience());
      break;
    }
    case AUTHENTICATION_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:google.api.BackendRule)
}

void BackendRule::SharedCtor() {
  selector_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  address_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&deadline_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&path_translation_) -
      reinterpret_cast<char*>(&deadline_)) + sizeof(path_translation_));
  clear_has_authentication();
}

BackendRule::~BackendRule() {
  // @@protoc_insertion_point(destructor:google.api.BackendRule)
  SharedDtor();
}

void BackendRule::SharedDtor() {
  selector_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  address_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (has_authentication()) {
    clear_authentication();
  }
}

void BackendRule::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* BackendRule::descriptor() {
  ::protobuf_google_2fapi_2fbackend_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fbackend_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const BackendRule& BackendRule::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fbackend_2eproto::scc_info_BackendRule.base);
  return *internal_default_instance();
}


void BackendRule::clear_authentication() {
// @@protoc_insertion_point(one_of_clear_start:google.api.BackendRule)
  switch (authentication_case()) {
    case kJwtAudience: {
      authentication_.jwt_audience_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
      break;
    }
    case AUTHENTICATION_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = AUTHENTICATION_NOT_SET;
}


void BackendRule::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.BackendRule)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  selector_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  address_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&deadline_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&path_translation_) -
      reinterpret_cast<char*>(&deadline_)) + sizeof(path_translation_));
  clear_authentication();
  _internal_metadata_.Clear();
}

bool BackendRule::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.BackendRule)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string selector = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_selector()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->selector().data(), static_cast<int>(this->selector().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.BackendRule.selector"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string address = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_address()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->address().data(), static_cast<int>(this->address().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.BackendRule.address"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double deadline = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u /* 25 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &deadline_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double min_deadline = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(33u /* 33 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &min_deadline_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double operation_deadline = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &operation_deadline_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.api.BackendRule.PathTranslation path_translation = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_path_translation(static_cast< ::google::api::BackendRule_PathTranslation >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string jwt_audience = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_jwt_audience()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->jwt_audience().data(), static_cast<int>(this->jwt_audience().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.BackendRule.jwt_audience"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.BackendRule)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.BackendRule)
  return false;
#undef DO_
}

void BackendRule::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.BackendRule)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string selector = 1;
  if (this->selector().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->selector().data(), static_cast<int>(this->selector().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.BackendRule.selector");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->selector(), output);
  }

  // string address = 2;
  if (this->address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->address().data(), static_cast<int>(this->address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.BackendRule.address");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->address(), output);
  }

  // double deadline = 3;
  if (this->deadline() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->deadline(), output);
  }

  // double min_deadline = 4;
  if (this->min_deadline() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->min_deadline(), output);
  }

  // double operation_deadline = 5;
  if (this->operation_deadline() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->operation_deadline(), output);
  }

  // .google.api.BackendRule.PathTranslation path_translation = 6;
  if (this->path_translation() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      6, this->path_translation(), output);
  }

  // string jwt_audience = 7;
  if (has_jwt_audience()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->jwt_audience().data(), static_cast<int>(this->jwt_audience().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.BackendRule.jwt_audience");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->jwt_audience(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.api.BackendRule)
}

::google::protobuf::uint8* BackendRule::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.api.BackendRule)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string selector = 1;
  if (this->selector().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->selector().data(), static_cast<int>(this->selector().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.BackendRule.selector");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->selector(), target);
  }

  // string address = 2;
  if (this->address().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->address().data(), static_cast<int>(this->address().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.BackendRule.address");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->address(), target);
  }

  // double deadline = 3;
  if (this->deadline() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->deadline(), target);
  }

  // double min_deadline = 4;
  if (this->min_deadline() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->min_deadline(), target);
  }

  // double operation_deadline = 5;
  if (this->operation_deadline() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->operation_deadline(), target);
  }

  // .google.api.BackendRule.PathTranslation path_translation = 6;
  if (this->path_translation() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      6, this->path_translation(), target);
  }

  // string jwt_audience = 7;
  if (has_jwt_audience()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->jwt_audience().data(), static_cast<int>(this->jwt_audience().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.BackendRule.jwt_audience");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->jwt_audience(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.BackendRule)
  return target;
}

size_t BackendRule::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.BackendRule)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string selector = 1;
  if (this->selector().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->selector());
  }

  // string address = 2;
  if (this->address().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->address());
  }

  // double deadline = 3;
  if (this->deadline() != 0) {
    total_size += 1 + 8;
  }

  // double min_deadline = 4;
  if (this->min_deadline() != 0) {
    total_size += 1 + 8;
  }

  // double operation_deadline = 5;
  if (this->operation_deadline() != 0) {
    total_size += 1 + 8;
  }

  // .google.api.BackendRule.PathTranslation path_translation = 6;
  if (this->path_translation() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->path_translation());
  }

  switch (authentication_case()) {
    // string jwt_audience = 7;
    case kJwtAudience: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->jwt_audience());
      break;
    }
    case AUTHENTICATION_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BackendRule::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.BackendRule)
  GOOGLE_DCHECK_NE(&from, this);
  const BackendRule* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BackendRule>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.BackendRule)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.BackendRule)
    MergeFrom(*source);
  }
}

void BackendRule::MergeFrom(const BackendRule& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.BackendRule)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.selector().size() > 0) {

    selector_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selector_);
  }
  if (from.address().size() > 0) {

    address_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.address_);
  }
  if (from.deadline() != 0) {
    set_deadline(from.deadline());
  }
  if (from.min_deadline() != 0) {
    set_min_deadline(from.min_deadline());
  }
  if (from.operation_deadline() != 0) {
    set_operation_deadline(from.operation_deadline());
  }
  if (from.path_translation() != 0) {
    set_path_translation(from.path_translation());
  }
  switch (from.authentication_case()) {
    case kJwtAudience: {
      set_jwt_audience(from.jwt_audience());
      break;
    }
    case AUTHENTICATION_NOT_SET: {
      break;
    }
  }
}

void BackendRule::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.BackendRule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BackendRule::CopyFrom(const BackendRule& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.BackendRule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BackendRule::IsInitialized() const {
  return true;
}

void BackendRule::Swap(BackendRule* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BackendRule::InternalSwap(BackendRule* other) {
  using std::swap;
  selector_.Swap(&other->selector_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  address_.Swap(&other->address_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(deadline_, other->deadline_);
  swap(min_deadline_, other->min_deadline_);
  swap(operation_deadline_, other->operation_deadline_);
  swap(path_translation_, other->path_translation_);
  swap(authentication_, other->authentication_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata BackendRule::GetMetadata() const {
  protobuf_google_2fapi_2fbackend_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fbackend_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace api
}  // namespace google
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::api::Backend* Arena::CreateMaybeMessage< ::google::api::Backend >(Arena* arena) {
  return Arena::CreateInternal< ::google::api::Backend >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::api::BackendRule* Arena::CreateMaybeMessage< ::google::api::BackendRule >(Arena* arena) {
  return Arena::CreateInternal< ::google::api::BackendRule >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
