contact_links:
  - name: ❓ Question and Help
    url: https://discord.com/invite/WaXnwUb
    about: The issue tracker is not for support questions. Please join our Taraxa community for help and discussion.