// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1beta1/source.proto

#ifndef PROTOBUF_INCLUDED_google_2fapi_2fexpr_2fv1beta1_2fsource_2eproto
#define PROTOBUF_INCLUDED_google_2fapi_2fexpr_2fv1beta1_2fsource_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fapi_2fexpr_2fv1beta1_2fsource_2eproto 

namespace protobuf_google_2fapi_2fexpr_2fv1beta1_2fsource_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_google_2fapi_2fexpr_2fv1beta1_2fsource_2eproto
namespace google {
namespace api {
namespace expr {
namespace v1beta1 {
class SourceInfo;
class SourceInfoDefaultTypeInternal;
extern SourceInfoDefaultTypeInternal _SourceInfo_default_instance_;
class SourceInfo_PositionsEntry_DoNotUse;
class SourceInfo_PositionsEntry_DoNotUseDefaultTypeInternal;
extern SourceInfo_PositionsEntry_DoNotUseDefaultTypeInternal _SourceInfo_PositionsEntry_DoNotUse_default_instance_;
class SourcePosition;
class SourcePositionDefaultTypeInternal;
extern SourcePositionDefaultTypeInternal _SourcePosition_default_instance_;
}  // namespace v1beta1
}  // namespace expr
}  // namespace api
}  // namespace google
namespace google {
namespace protobuf {
template<> ::google::api::expr::v1beta1::SourceInfo* Arena::CreateMaybeMessage<::google::api::expr::v1beta1::SourceInfo>(Arena*);
template<> ::google::api::expr::v1beta1::SourceInfo_PositionsEntry_DoNotUse* Arena::CreateMaybeMessage<::google::api::expr::v1beta1::SourceInfo_PositionsEntry_DoNotUse>(Arena*);
template<> ::google::api::expr::v1beta1::SourcePosition* Arena::CreateMaybeMessage<::google::api::expr::v1beta1::SourcePosition>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace google {
namespace api {
namespace expr {
namespace v1beta1 {

// ===================================================================

class SourceInfo_PositionsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SourceInfo_PositionsEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SourceInfo_PositionsEntry_DoNotUse, 
    ::google::protobuf::int32, ::google::protobuf::int32,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
    0 > SuperType;
  SourceInfo_PositionsEntry_DoNotUse();
  SourceInfo_PositionsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SourceInfo_PositionsEntry_DoNotUse& other);
  static const SourceInfo_PositionsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SourceInfo_PositionsEntry_DoNotUse*>(&_SourceInfo_PositionsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) final;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SourceInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.api.expr.v1beta1.SourceInfo) */ {
 public:
  SourceInfo();
  virtual ~SourceInfo();

  SourceInfo(const SourceInfo& from);

  inline SourceInfo& operator=(const SourceInfo& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SourceInfo(SourceInfo&& from) noexcept
    : SourceInfo() {
    *this = ::std::move(from);
  }

  inline SourceInfo& operator=(SourceInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const SourceInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SourceInfo* internal_default_instance() {
    return reinterpret_cast<const SourceInfo*>(
               &_SourceInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void UnsafeArenaSwap(SourceInfo* other);
  void Swap(SourceInfo* other);
  friend void swap(SourceInfo& a, SourceInfo& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SourceInfo* New() const final {
    return CreateMaybeMessage<SourceInfo>(NULL);
  }

  SourceInfo* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SourceInfo>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SourceInfo& from);
  void MergeFrom(const SourceInfo& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SourceInfo* other);
  protected:
  explicit SourceInfo(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // repeated int32 line_offsets = 3;
  int line_offsets_size() const;
  void clear_line_offsets();
  static const int kLineOffsetsFieldNumber = 3;
  ::google::protobuf::int32 line_offsets(int index) const;
  void set_line_offsets(int index, ::google::protobuf::int32 value);
  void add_line_offsets(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      line_offsets() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_line_offsets();

  // map<int32, int32> positions = 4;
  int positions_size() const;
  void clear_positions();
  static const int kPositionsFieldNumber = 4;
  const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
      positions() const;
  ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
      mutable_positions();

  // string location = 2;
  void clear_location();
  static const int kLocationFieldNumber = 2;
  const ::std::string& location() const;
  void set_location(const ::std::string& value);
  #if LANG_CXX11
  void set_location(::std::string&& value);
  #endif
  void set_location(const char* value);
  void set_location(const char* value, size_t size);
  ::std::string* mutable_location();
  ::std::string* release_location();
  void set_allocated_location(::std::string* location);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_location();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_location(
      ::std::string* location);

  // @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.SourceInfo)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > line_offsets_;
  mutable int _line_offsets_cached_byte_size_;
  ::google::protobuf::internal::MapField<
      SourceInfo_PositionsEntry_DoNotUse,
      ::google::protobuf::int32, ::google::protobuf::int32,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      ::google::protobuf::internal::WireFormatLite::TYPE_INT32,
      0 > positions_;
  ::google::protobuf::internal::ArenaStringPtr location_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fsource_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class SourcePosition : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:google.api.expr.v1beta1.SourcePosition) */ {
 public:
  SourcePosition();
  virtual ~SourcePosition();

  SourcePosition(const SourcePosition& from);

  inline SourcePosition& operator=(const SourcePosition& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SourcePosition(SourcePosition&& from) noexcept
    : SourcePosition() {
    *this = ::std::move(from);
  }

  inline SourcePosition& operator=(SourcePosition&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const final {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const final {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const SourcePosition& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SourcePosition* internal_default_instance() {
    return reinterpret_cast<const SourcePosition*>(
               &_SourcePosition_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void UnsafeArenaSwap(SourcePosition* other);
  void Swap(SourcePosition* other);
  friend void swap(SourcePosition& a, SourcePosition& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SourcePosition* New() const final {
    return CreateMaybeMessage<SourcePosition>(NULL);
  }

  SourcePosition* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<SourcePosition>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const SourcePosition& from);
  void MergeFrom(const SourcePosition& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SourcePosition* other);
  protected:
  explicit SourcePosition(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string location = 1;
  void clear_location();
  static const int kLocationFieldNumber = 1;
  const ::std::string& location() const;
  void set_location(const ::std::string& value);
  #if LANG_CXX11
  void set_location(::std::string&& value);
  #endif
  void set_location(const char* value);
  void set_location(const char* value, size_t size);
  ::std::string* mutable_location();
  ::std::string* release_location();
  void set_allocated_location(::std::string* location);
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  ::std::string* unsafe_arena_release_location();
  PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_location(
      ::std::string* location);

  // int32 offset = 2;
  void clear_offset();
  static const int kOffsetFieldNumber = 2;
  ::google::protobuf::int32 offset() const;
  void set_offset(::google::protobuf::int32 value);

  // int32 line = 3;
  void clear_line();
  static const int kLineFieldNumber = 3;
  ::google::protobuf::int32 line() const;
  void set_line(::google::protobuf::int32 value);

  // int32 column = 4;
  void clear_column();
  static const int kColumnFieldNumber = 4;
  ::google::protobuf::int32 column() const;
  void set_column(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:google.api.expr.v1beta1.SourcePosition)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::ArenaStringPtr location_;
  ::google::protobuf::int32 offset_;
  ::google::protobuf::int32 line_;
  ::google::protobuf::int32 column_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fsource_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SourceInfo

// string location = 2;
inline void SourceInfo::clear_location() {
  location_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& SourceInfo::location() const {
  // @@protoc_insertion_point(field_get:google.api.expr.v1beta1.SourceInfo.location)
  return location_.Get();
}
inline void SourceInfo::set_location(const ::std::string& value) {
  
  location_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.expr.v1beta1.SourceInfo.location)
}
#if LANG_CXX11
inline void SourceInfo::set_location(::std::string&& value) {
  
  location_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:google.api.expr.v1beta1.SourceInfo.location)
}
#endif
inline void SourceInfo::set_location(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  location_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.expr.v1beta1.SourceInfo.location)
}
inline void SourceInfo::set_location(const char* value,
    size_t size) {
  
  location_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.expr.v1beta1.SourceInfo.location)
}
inline ::std::string* SourceInfo::mutable_location() {
  
  // @@protoc_insertion_point(field_mutable:google.api.expr.v1beta1.SourceInfo.location)
  return location_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* SourceInfo::release_location() {
  // @@protoc_insertion_point(field_release:google.api.expr.v1beta1.SourceInfo.location)
  
  return location_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void SourceInfo::set_allocated_location(::std::string* location) {
  if (location != NULL) {
    
  } else {
    
  }
  location_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), location,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:google.api.expr.v1beta1.SourceInfo.location)
}
inline ::std::string* SourceInfo::unsafe_arena_release_location() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.expr.v1beta1.SourceInfo.location)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return location_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void SourceInfo::unsafe_arena_set_allocated_location(
    ::std::string* location) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (location != NULL) {
    
  } else {
    
  }
  location_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      location, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.expr.v1beta1.SourceInfo.location)
}

// repeated int32 line_offsets = 3;
inline int SourceInfo::line_offsets_size() const {
  return line_offsets_.size();
}
inline void SourceInfo::clear_line_offsets() {
  line_offsets_.Clear();
}
inline ::google::protobuf::int32 SourceInfo::line_offsets(int index) const {
  // @@protoc_insertion_point(field_get:google.api.expr.v1beta1.SourceInfo.line_offsets)
  return line_offsets_.Get(index);
}
inline void SourceInfo::set_line_offsets(int index, ::google::protobuf::int32 value) {
  line_offsets_.Set(index, value);
  // @@protoc_insertion_point(field_set:google.api.expr.v1beta1.SourceInfo.line_offsets)
}
inline void SourceInfo::add_line_offsets(::google::protobuf::int32 value) {
  line_offsets_.Add(value);
  // @@protoc_insertion_point(field_add:google.api.expr.v1beta1.SourceInfo.line_offsets)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
SourceInfo::line_offsets() const {
  // @@protoc_insertion_point(field_list:google.api.expr.v1beta1.SourceInfo.line_offsets)
  return line_offsets_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
SourceInfo::mutable_line_offsets() {
  // @@protoc_insertion_point(field_mutable_list:google.api.expr.v1beta1.SourceInfo.line_offsets)
  return &line_offsets_;
}

// map<int32, int32> positions = 4;
inline int SourceInfo::positions_size() const {
  return positions_.size();
}
inline void SourceInfo::clear_positions() {
  positions_.Clear();
}
inline const ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >&
SourceInfo::positions() const {
  // @@protoc_insertion_point(field_map:google.api.expr.v1beta1.SourceInfo.positions)
  return positions_.GetMap();
}
inline ::google::protobuf::Map< ::google::protobuf::int32, ::google::protobuf::int32 >*
SourceInfo::mutable_positions() {
  // @@protoc_insertion_point(field_mutable_map:google.api.expr.v1beta1.SourceInfo.positions)
  return positions_.MutableMap();
}

// -------------------------------------------------------------------

// SourcePosition

// string location = 1;
inline void SourcePosition::clear_location() {
  location_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline const ::std::string& SourcePosition::location() const {
  // @@protoc_insertion_point(field_get:google.api.expr.v1beta1.SourcePosition.location)
  return location_.Get();
}
inline void SourcePosition::set_location(const ::std::string& value) {
  
  location_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:google.api.expr.v1beta1.SourcePosition.location)
}
#if LANG_CXX11
inline void SourcePosition::set_location(::std::string&& value) {
  
  location_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:google.api.expr.v1beta1.SourcePosition.location)
}
#endif
inline void SourcePosition::set_location(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  location_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:google.api.expr.v1beta1.SourcePosition.location)
}
inline void SourcePosition::set_location(const char* value,
    size_t size) {
  
  location_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:google.api.expr.v1beta1.SourcePosition.location)
}
inline ::std::string* SourcePosition::mutable_location() {
  
  // @@protoc_insertion_point(field_mutable:google.api.expr.v1beta1.SourcePosition.location)
  return location_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline ::std::string* SourcePosition::release_location() {
  // @@protoc_insertion_point(field_release:google.api.expr.v1beta1.SourcePosition.location)
  
  return location_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
inline void SourcePosition::set_allocated_location(::std::string* location) {
  if (location != NULL) {
    
  } else {
    
  }
  location_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), location,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:google.api.expr.v1beta1.SourcePosition.location)
}
inline ::std::string* SourcePosition::unsafe_arena_release_location() {
  // @@protoc_insertion_point(field_unsafe_arena_release:google.api.expr.v1beta1.SourcePosition.location)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return location_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
inline void SourcePosition::unsafe_arena_set_allocated_location(
    ::std::string* location) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (location != NULL) {
    
  } else {
    
  }
  location_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      location, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.expr.v1beta1.SourcePosition.location)
}

// int32 offset = 2;
inline void SourcePosition::clear_offset() {
  offset_ = 0;
}
inline ::google::protobuf::int32 SourcePosition::offset() const {
  // @@protoc_insertion_point(field_get:google.api.expr.v1beta1.SourcePosition.offset)
  return offset_;
}
inline void SourcePosition::set_offset(::google::protobuf::int32 value) {
  
  offset_ = value;
  // @@protoc_insertion_point(field_set:google.api.expr.v1beta1.SourcePosition.offset)
}

// int32 line = 3;
inline void SourcePosition::clear_line() {
  line_ = 0;
}
inline ::google::protobuf::int32 SourcePosition::line() const {
  // @@protoc_insertion_point(field_get:google.api.expr.v1beta1.SourcePosition.line)
  return line_;
}
inline void SourcePosition::set_line(::google::protobuf::int32 value) {
  
  line_ = value;
  // @@protoc_insertion_point(field_set:google.api.expr.v1beta1.SourcePosition.line)
}

// int32 column = 4;
inline void SourcePosition::clear_column() {
  column_ = 0;
}
inline ::google::protobuf::int32 SourcePosition::column() const {
  // @@protoc_insertion_point(field_get:google.api.expr.v1beta1.SourcePosition.column)
  return column_;
}
inline void SourcePosition::set_column(::google::protobuf::int32 value) {
  
  column_ = value;
  // @@protoc_insertion_point(field_set:google.api.expr.v1beta1.SourcePosition.column)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1beta1
}  // namespace expr
}  // namespace api
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_google_2fapi_2fexpr_2fv1beta1_2fsource_2eproto
