// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/api/expr/v1beta1/value.proto

#include "google/api/expr/v1beta1/value.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_EnumValue;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_ListValue;
}  // namespace protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto
namespace protobuf_google_2fprotobuf_2fany_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2fany_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Any;
}  // namespace protobuf_google_2fprotobuf_2fany_2eproto
namespace google {
namespace api {
namespace expr {
namespace v1beta1 {
class ValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Value>
      _instance;
  int null_value_;
  bool bool_value_;
  ::google::protobuf::int64 int64_value_;
  ::google::protobuf::uint64 uint64_value_;
  double double_value_;
  ::google::protobuf::internal::ArenaStringPtr string_value_;
  ::google::protobuf::internal::ArenaStringPtr bytes_value_;
  const ::google::api::expr::v1beta1::EnumValue* enum_value_;
  const ::google::protobuf::Any* object_value_;
  const ::google::api::expr::v1beta1::MapValue* map_value_;
  const ::google::api::expr::v1beta1::ListValue* list_value_;
  ::google::protobuf::internal::ArenaStringPtr type_value_;
} _Value_default_instance_;
class EnumValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EnumValue>
      _instance;
} _EnumValue_default_instance_;
class ListValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ListValue>
      _instance;
} _ListValue_default_instance_;
class MapValue_EntryDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MapValue_Entry>
      _instance;
} _MapValue_Entry_default_instance_;
class MapValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MapValue>
      _instance;
} _MapValue_default_instance_;
}  // namespace v1beta1
}  // namespace expr
}  // namespace api
}  // namespace google
namespace protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto {
static void InitDefaultsEnumValue() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::api::expr::v1beta1::_EnumValue_default_instance_;
    new (ptr) ::google::api::expr::v1beta1::EnumValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::api::expr::v1beta1::EnumValue::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_EnumValue =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsEnumValue}, {}};

static void InitDefaultsListValue() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::api::expr::v1beta1::_Value_default_instance_;
    new (ptr) ::google::api::expr::v1beta1::Value();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  {
    void* ptr = &::google::api::expr::v1beta1::_ListValue_default_instance_;
    new (ptr) ::google::api::expr::v1beta1::ListValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  {
    void* ptr = &::google::api::expr::v1beta1::_MapValue_Entry_default_instance_;
    new (ptr) ::google::api::expr::v1beta1::MapValue_Entry();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  {
    void* ptr = &::google::api::expr::v1beta1::_MapValue_default_instance_;
    new (ptr) ::google::api::expr::v1beta1::MapValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::api::expr::v1beta1::Value::InitAsDefaultInstance();
  ::google::api::expr::v1beta1::ListValue::InitAsDefaultInstance();
  ::google::api::expr::v1beta1::MapValue_Entry::InitAsDefaultInstance();
  ::google::api::expr::v1beta1::MapValue::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ListValue =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsListValue}, {
      &protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_EnumValue.base,
      &protobuf_google_2fprotobuf_2fany_2eproto::scc_info_Any.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_EnumValue.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ListValue.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::Value, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::Value, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, null_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, bool_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, int64_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, uint64_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, double_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, string_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, bytes_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, enum_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, object_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, map_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, list_value_),
  offsetof(::google::api::expr::v1beta1::ValueDefaultTypeInternal, type_value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::Value, kind_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::EnumValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::EnumValue, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::EnumValue, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::ListValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::ListValue, values_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::MapValue_Entry, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::MapValue_Entry, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::MapValue_Entry, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::MapValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::api::expr::v1beta1::MapValue, entries_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::google::api::expr::v1beta1::Value)},
  { 18, -1, sizeof(::google::api::expr::v1beta1::EnumValue)},
  { 25, -1, sizeof(::google::api::expr::v1beta1::ListValue)},
  { 31, -1, sizeof(::google::api::expr::v1beta1::MapValue_Entry)},
  { 38, -1, sizeof(::google::api::expr::v1beta1::MapValue)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::api::expr::v1beta1::_Value_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::api::expr::v1beta1::_EnumValue_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::api::expr::v1beta1::_ListValue_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::api::expr::v1beta1::_MapValue_Entry_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::api::expr::v1beta1::_MapValue_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "google/api/expr/v1beta1/value.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n#google/api/expr/v1beta1/value.proto\022\027g"
      "oogle.api.expr.v1beta1\032\031google/protobuf/"
      "any.proto\032\034google/protobuf/struct.proto\""
      "\275\003\n\005Value\0220\n\nnull_value\030\001 \001(\0162\032.google.p"
      "rotobuf.NullValueH\000\022\024\n\nbool_value\030\002 \001(\010H"
      "\000\022\025\n\013int64_value\030\003 \001(\003H\000\022\026\n\014uint64_value"
      "\030\004 \001(\004H\000\022\026\n\014double_value\030\005 \001(\001H\000\022\026\n\014stri"
      "ng_value\030\006 \001(\tH\000\022\025\n\013bytes_value\030\007 \001(\014H\000\022"
      "8\n\nenum_value\030\t \001(\0132\".google.api.expr.v1"
      "beta1.EnumValueH\000\022,\n\014object_value\030\n \001(\0132"
      "\024.google.protobuf.AnyH\000\0226\n\tmap_value\030\013 \001"
      "(\0132!.google.api.expr.v1beta1.MapValueH\000\022"
      "8\n\nlist_value\030\014 \001(\0132\".google.api.expr.v1"
      "beta1.ListValueH\000\022\024\n\ntype_value\030\017 \001(\tH\000B"
      "\006\n\004kind\"(\n\tEnumValue\022\014\n\004type\030\001 \001(\t\022\r\n\005va"
      "lue\030\002 \001(\005\";\n\tListValue\022.\n\006values\030\001 \003(\0132\036"
      ".google.api.expr.v1beta1.Value\"\251\001\n\010MapVa"
      "lue\0228\n\007entries\030\001 \003(\0132\'.google.api.expr.v"
      "1beta1.MapValue.Entry\032c\n\005Entry\022+\n\003key\030\001 "
      "\001(\0132\036.google.api.expr.v1beta1.Value\022-\n\005v"
      "alue\030\002 \001(\0132\036.google.api.expr.v1beta1.Val"
      "ueBk\n\033com.google.api.expr.v1beta1B\nValue"
      "ProtoP\001Z;google.golang.org/genproto/goog"
      "leapis/api/expr/v1beta1;expr\370\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 959);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "google/api/expr/v1beta1/value.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2fstruct_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto
namespace google {
namespace api {
namespace expr {
namespace v1beta1 {

// ===================================================================

void Value::InitAsDefaultInstance() {
  ::google::api::expr::v1beta1::_Value_default_instance_.null_value_ = 0;
  ::google::api::expr::v1beta1::_Value_default_instance_.bool_value_ = false;
  ::google::api::expr::v1beta1::_Value_default_instance_.int64_value_ = GOOGLE_LONGLONG(0);
  ::google::api::expr::v1beta1::_Value_default_instance_.uint64_value_ = GOOGLE_ULONGLONG(0);
  ::google::api::expr::v1beta1::_Value_default_instance_.double_value_ = 0;
  ::google::api::expr::v1beta1::_Value_default_instance_.string_value_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::google::api::expr::v1beta1::_Value_default_instance_.bytes_value_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::google::api::expr::v1beta1::_Value_default_instance_.enum_value_ = const_cast< ::google::api::expr::v1beta1::EnumValue*>(
      ::google::api::expr::v1beta1::EnumValue::internal_default_instance());
  ::google::api::expr::v1beta1::_Value_default_instance_.object_value_ = const_cast< ::google::protobuf::Any*>(
      ::google::protobuf::Any::internal_default_instance());
  ::google::api::expr::v1beta1::_Value_default_instance_.map_value_ = const_cast< ::google::api::expr::v1beta1::MapValue*>(
      ::google::api::expr::v1beta1::MapValue::internal_default_instance());
  ::google::api::expr::v1beta1::_Value_default_instance_.list_value_ = const_cast< ::google::api::expr::v1beta1::ListValue*>(
      ::google::api::expr::v1beta1::ListValue::internal_default_instance());
  ::google::api::expr::v1beta1::_Value_default_instance_.type_value_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Value::set_allocated_enum_value(::google::api::expr::v1beta1::EnumValue* enum_value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_kind();
  if (enum_value) {
    ::google::protobuf::Arena* submessage_arena =
      ::google::protobuf::Arena::GetArena(enum_value);
    if (message_arena != submessage_arena) {
      enum_value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, enum_value, submessage_arena);
    }
    set_has_enum_value();
    kind_.enum_value_ = enum_value;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.expr.v1beta1.Value.enum_value)
}
void Value::set_allocated_object_value(::google::protobuf::Any* object_value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_kind();
  if (object_value) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      object_value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, object_value, submessage_arena);
    }
    set_has_object_value();
    kind_.object_value_ = object_value;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.expr.v1beta1.Value.object_value)
}
void Value::clear_object_value() {
  if (has_object_value()) {
    if (GetArenaNoVirtual() == NULL) {
      delete kind_.object_value_;
    }
    clear_has_kind();
  }
}
void Value::set_allocated_map_value(::google::api::expr::v1beta1::MapValue* map_value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_kind();
  if (map_value) {
    ::google::protobuf::Arena* submessage_arena =
      ::google::protobuf::Arena::GetArena(map_value);
    if (message_arena != submessage_arena) {
      map_value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, map_value, submessage_arena);
    }
    set_has_map_value();
    kind_.map_value_ = map_value;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.expr.v1beta1.Value.map_value)
}
void Value::set_allocated_list_value(::google::api::expr::v1beta1::ListValue* list_value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_kind();
  if (list_value) {
    ::google::protobuf::Arena* submessage_arena =
      ::google::protobuf::Arena::GetArena(list_value);
    if (message_arena != submessage_arena) {
      list_value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, list_value, submessage_arena);
    }
    set_has_list_value();
    kind_.list_value_ = list_value;
  }
  // @@protoc_insertion_point(field_set_allocated:google.api.expr.v1beta1.Value.list_value)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Value::kNullValueFieldNumber;
const int Value::kBoolValueFieldNumber;
const int Value::kInt64ValueFieldNumber;
const int Value::kUint64ValueFieldNumber;
const int Value::kDoubleValueFieldNumber;
const int Value::kStringValueFieldNumber;
const int Value::kBytesValueFieldNumber;
const int Value::kEnumValueFieldNumber;
const int Value::kObjectValueFieldNumber;
const int Value::kMapValueFieldNumber;
const int Value::kListValueFieldNumber;
const int Value::kTypeValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Value::Value()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.expr.v1beta1.Value)
}
Value::Value(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.api.expr.v1beta1.Value)
}
Value::Value(const Value& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_kind();
  switch (from.kind_case()) {
    case kNullValue: {
      set_null_value(from.null_value());
      break;
    }
    case kBoolValue: {
      set_bool_value(from.bool_value());
      break;
    }
    case kInt64Value: {
      set_int64_value(from.int64_value());
      break;
    }
    case kUint64Value: {
      set_uint64_value(from.uint64_value());
      break;
    }
    case kDoubleValue: {
      set_double_value(from.double_value());
      break;
    }
    case kStringValue: {
      set_string_value(from.string_value());
      break;
    }
    case kBytesValue: {
      set_bytes_value(from.bytes_value());
      break;
    }
    case kEnumValue: {
      mutable_enum_value()->::google::api::expr::v1beta1::EnumValue::MergeFrom(from.enum_value());
      break;
    }
    case kObjectValue: {
      mutable_object_value()->::google::protobuf::Any::MergeFrom(from.object_value());
      break;
    }
    case kMapValue: {
      mutable_map_value()->::google::api::expr::v1beta1::MapValue::MergeFrom(from.map_value());
      break;
    }
    case kListValue: {
      mutable_list_value()->::google::api::expr::v1beta1::ListValue::MergeFrom(from.list_value());
      break;
    }
    case kTypeValue: {
      set_type_value(from.type_value());
      break;
    }
    case KIND_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:google.api.expr.v1beta1.Value)
}

void Value::SharedCtor() {
  clear_has_kind();
}

Value::~Value() {
  // @@protoc_insertion_point(destructor:google.api.expr.v1beta1.Value)
  SharedDtor();
}

void Value::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
  if (has_kind()) {
    clear_kind();
  }
}

void Value::ArenaDtor(void* object) {
  Value* _this = reinterpret_cast< Value* >(object);
  (void)_this;
}
void Value::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void Value::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Value::descriptor() {
  ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Value& Value::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  return *internal_default_instance();
}


void Value::clear_kind() {
// @@protoc_insertion_point(one_of_clear_start:google.api.expr.v1beta1.Value)
  switch (kind_case()) {
    case kNullValue: {
      // No need to clear
      break;
    }
    case kBoolValue: {
      // No need to clear
      break;
    }
    case kInt64Value: {
      // No need to clear
      break;
    }
    case kUint64Value: {
      // No need to clear
      break;
    }
    case kDoubleValue: {
      // No need to clear
      break;
    }
    case kStringValue: {
      kind_.string_value_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case kBytesValue: {
      kind_.bytes_value_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case kEnumValue: {
      if (GetArenaNoVirtual() == NULL) {
        delete kind_.enum_value_;
      }
      break;
    }
    case kObjectValue: {
      if (GetArenaNoVirtual() == NULL) {
        delete kind_.object_value_;
      }
      break;
    }
    case kMapValue: {
      if (GetArenaNoVirtual() == NULL) {
        delete kind_.map_value_;
      }
      break;
    }
    case kListValue: {
      if (GetArenaNoVirtual() == NULL) {
        delete kind_.list_value_;
      }
      break;
    }
    case kTypeValue: {
      kind_.type_value_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
          GetArenaNoVirtual());
      break;
    }
    case KIND_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = KIND_NOT_SET;
}


void Value::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.expr.v1beta1.Value)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_kind();
  _internal_metadata_.Clear();
}

bool Value::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.expr.v1beta1.Value)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .google.protobuf.NullValue null_value = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_null_value(static_cast< ::google::protobuf::NullValue >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool bool_value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          clear_kind();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &kind_.bool_value_)));
          set_has_bool_value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 int64_value = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          clear_kind();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &kind_.int64_value_)));
          set_has_int64_value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 uint64_value = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          clear_kind();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &kind_.uint64_value_)));
          set_has_uint64_value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // double double_value = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(41u /* 41 & 0xFF */)) {
          clear_kind();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &kind_.double_value_)));
          set_has_double_value();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string string_value = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_string_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->string_value().data(), static_cast<int>(this->string_value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.expr.v1beta1.Value.string_value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes bytes_value = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_bytes_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.api.expr.v1beta1.EnumValue enum_value = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_enum_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Any object_value = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_object_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.api.expr.v1beta1.MapValue map_value = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_map_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.api.expr.v1beta1.ListValue list_value = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_list_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string type_value = 15;
      case 15: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(122u /* 122 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->type_value().data(), static_cast<int>(this->type_value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.expr.v1beta1.Value.type_value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.expr.v1beta1.Value)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.expr.v1beta1.Value)
  return false;
#undef DO_
}

void Value::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.expr.v1beta1.Value)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.NullValue null_value = 1;
  if (has_null_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->null_value(), output);
  }

  // bool bool_value = 2;
  if (has_bool_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->bool_value(), output);
  }

  // int64 int64_value = 3;
  if (has_int64_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->int64_value(), output);
  }

  // uint64 uint64_value = 4;
  if (has_uint64_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(4, this->uint64_value(), output);
  }

  // double double_value = 5;
  if (has_double_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->double_value(), output);
  }

  // string string_value = 6;
  if (has_string_value()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string_value().data(), static_cast<int>(this->string_value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.expr.v1beta1.Value.string_value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->string_value(), output);
  }

  // bytes bytes_value = 7;
  if (has_bytes_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      7, this->bytes_value(), output);
  }

  // .google.api.expr.v1beta1.EnumValue enum_value = 9;
  if (has_enum_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, this->_internal_enum_value(), output);
  }

  // .google.protobuf.Any object_value = 10;
  if (has_object_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10, this->_internal_object_value(), output);
  }

  // .google.api.expr.v1beta1.MapValue map_value = 11;
  if (has_map_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      11, this->_internal_map_value(), output);
  }

  // .google.api.expr.v1beta1.ListValue list_value = 12;
  if (has_list_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      12, this->_internal_list_value(), output);
  }

  // string type_value = 15;
  if (has_type_value()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type_value().data(), static_cast<int>(this->type_value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.expr.v1beta1.Value.type_value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      15, this->type_value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.api.expr.v1beta1.Value)
}

::google::protobuf::uint8* Value::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.api.expr.v1beta1.Value)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.NullValue null_value = 1;
  if (has_null_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->null_value(), target);
  }

  // bool bool_value = 2;
  if (has_bool_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->bool_value(), target);
  }

  // int64 int64_value = 3;
  if (has_int64_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->int64_value(), target);
  }

  // uint64 uint64_value = 4;
  if (has_uint64_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(4, this->uint64_value(), target);
  }

  // double double_value = 5;
  if (has_double_value()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->double_value(), target);
  }

  // string string_value = 6;
  if (has_string_value()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->string_value().data(), static_cast<int>(this->string_value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.expr.v1beta1.Value.string_value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->string_value(), target);
  }

  // bytes bytes_value = 7;
  if (has_bytes_value()) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        7, this->bytes_value(), target);
  }

  // .google.api.expr.v1beta1.EnumValue enum_value = 9;
  if (has_enum_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        9, this->_internal_enum_value(), deterministic, target);
  }

  // .google.protobuf.Any object_value = 10;
  if (has_object_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        10, this->_internal_object_value(), deterministic, target);
  }

  // .google.api.expr.v1beta1.MapValue map_value = 11;
  if (has_map_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        11, this->_internal_map_value(), deterministic, target);
  }

  // .google.api.expr.v1beta1.ListValue list_value = 12;
  if (has_list_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        12, this->_internal_list_value(), deterministic, target);
  }

  // string type_value = 15;
  if (has_type_value()) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type_value().data(), static_cast<int>(this->type_value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.expr.v1beta1.Value.type_value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        15, this->type_value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.expr.v1beta1.Value)
  return target;
}

size_t Value::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.expr.v1beta1.Value)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  switch (kind_case()) {
    // .google.protobuf.NullValue null_value = 1;
    case kNullValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->null_value());
      break;
    }
    // bool bool_value = 2;
    case kBoolValue: {
      total_size += 1 + 1;
      break;
    }
    // int64 int64_value = 3;
    case kInt64Value: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->int64_value());
      break;
    }
    // uint64 uint64_value = 4;
    case kUint64Value: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->uint64_value());
      break;
    }
    // double double_value = 5;
    case kDoubleValue: {
      total_size += 1 + 8;
      break;
    }
    // string string_value = 6;
    case kStringValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->string_value());
      break;
    }
    // bytes bytes_value = 7;
    case kBytesValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::BytesSize(
          this->bytes_value());
      break;
    }
    // .google.api.expr.v1beta1.EnumValue enum_value = 9;
    case kEnumValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *kind_.enum_value_);
      break;
    }
    // .google.protobuf.Any object_value = 10;
    case kObjectValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *kind_.object_value_);
      break;
    }
    // .google.api.expr.v1beta1.MapValue map_value = 11;
    case kMapValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *kind_.map_value_);
      break;
    }
    // .google.api.expr.v1beta1.ListValue list_value = 12;
    case kListValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *kind_.list_value_);
      break;
    }
    // string type_value = 15;
    case kTypeValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->type_value());
      break;
    }
    case KIND_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Value::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.expr.v1beta1.Value)
  GOOGLE_DCHECK_NE(&from, this);
  const Value* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Value>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.expr.v1beta1.Value)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.expr.v1beta1.Value)
    MergeFrom(*source);
  }
}

void Value::MergeFrom(const Value& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.expr.v1beta1.Value)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.kind_case()) {
    case kNullValue: {
      set_null_value(from.null_value());
      break;
    }
    case kBoolValue: {
      set_bool_value(from.bool_value());
      break;
    }
    case kInt64Value: {
      set_int64_value(from.int64_value());
      break;
    }
    case kUint64Value: {
      set_uint64_value(from.uint64_value());
      break;
    }
    case kDoubleValue: {
      set_double_value(from.double_value());
      break;
    }
    case kStringValue: {
      set_string_value(from.string_value());
      break;
    }
    case kBytesValue: {
      set_bytes_value(from.bytes_value());
      break;
    }
    case kEnumValue: {
      mutable_enum_value()->::google::api::expr::v1beta1::EnumValue::MergeFrom(from.enum_value());
      break;
    }
    case kObjectValue: {
      mutable_object_value()->::google::protobuf::Any::MergeFrom(from.object_value());
      break;
    }
    case kMapValue: {
      mutable_map_value()->::google::api::expr::v1beta1::MapValue::MergeFrom(from.map_value());
      break;
    }
    case kListValue: {
      mutable_list_value()->::google::api::expr::v1beta1::ListValue::MergeFrom(from.list_value());
      break;
    }
    case kTypeValue: {
      set_type_value(from.type_value());
      break;
    }
    case KIND_NOT_SET: {
      break;
    }
  }
}

void Value::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.expr.v1beta1.Value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Value::CopyFrom(const Value& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.expr.v1beta1.Value)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Value::IsInitialized() const {
  return true;
}

void Value::Swap(Value* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    Value* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void Value::UnsafeArenaSwap(Value* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void Value::InternalSwap(Value* other) {
  using std::swap;
  swap(kind_, other->kind_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Value::GetMetadata() const {
  protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void EnumValue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EnumValue::kTypeFieldNumber;
const int EnumValue::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EnumValue::EnumValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_EnumValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.expr.v1beta1.EnumValue)
}
EnumValue::EnumValue(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_EnumValue.base);
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.api.expr.v1beta1.EnumValue)
}
EnumValue::EnumValue(const EnumValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.type().size() > 0) {
    type_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type(),
      GetArenaNoVirtual());
  }
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:google.api.expr.v1beta1.EnumValue)
}

void EnumValue::SharedCtor() {
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_ = 0;
}

EnumValue::~EnumValue() {
  // @@protoc_insertion_point(destructor:google.api.expr.v1beta1.EnumValue)
  SharedDtor();
}

void EnumValue::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void EnumValue::ArenaDtor(void* object) {
  EnumValue* _this = reinterpret_cast< EnumValue* >(object);
  (void)_this;
}
void EnumValue::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void EnumValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* EnumValue::descriptor() {
  ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EnumValue& EnumValue::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_EnumValue.base);
  return *internal_default_instance();
}


void EnumValue::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.expr.v1beta1.EnumValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  type_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  value_ = 0;
  _internal_metadata_.Clear();
}

bool EnumValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.expr.v1beta1.EnumValue)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.api.expr.v1beta1.EnumValue.type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.expr.v1beta1.EnumValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.expr.v1beta1.EnumValue)
  return false;
#undef DO_
}

void EnumValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.expr.v1beta1.EnumValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.expr.v1beta1.EnumValue.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  // int32 value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.api.expr.v1beta1.EnumValue)
}

::google::protobuf::uint8* EnumValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.api.expr.v1beta1.EnumValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.api.expr.v1beta1.EnumValue.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  // int32 value = 2;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.expr.v1beta1.EnumValue)
  return target;
}

size_t EnumValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.expr.v1beta1.EnumValue)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string type = 1;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  // int32 value = 2;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void EnumValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.expr.v1beta1.EnumValue)
  GOOGLE_DCHECK_NE(&from, this);
  const EnumValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EnumValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.expr.v1beta1.EnumValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.expr.v1beta1.EnumValue)
    MergeFrom(*source);
  }
}

void EnumValue::MergeFrom(const EnumValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.expr.v1beta1.EnumValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type().size() > 0) {
    set_type(from.type());
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void EnumValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.expr.v1beta1.EnumValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EnumValue::CopyFrom(const EnumValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.expr.v1beta1.EnumValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EnumValue::IsInitialized() const {
  return true;
}

void EnumValue::Swap(EnumValue* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    EnumValue* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void EnumValue::UnsafeArenaSwap(EnumValue* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void EnumValue::InternalSwap(EnumValue* other) {
  using std::swap;
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata EnumValue::GetMetadata() const {
  protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ListValue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ListValue::kValuesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ListValue::ListValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.expr.v1beta1.ListValue)
}
ListValue::ListValue(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  values_(arena) {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.api.expr.v1beta1.ListValue)
}
ListValue::ListValue(const ListValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      values_(from.values_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.api.expr.v1beta1.ListValue)
}

void ListValue::SharedCtor() {
}

ListValue::~ListValue() {
  // @@protoc_insertion_point(destructor:google.api.expr.v1beta1.ListValue)
  SharedDtor();
}

void ListValue::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
}

void ListValue::ArenaDtor(void* object) {
  ListValue* _this = reinterpret_cast< ListValue* >(object);
  (void)_this;
}
void ListValue::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ListValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ListValue::descriptor() {
  ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ListValue& ListValue::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  return *internal_default_instance();
}


void ListValue::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.expr.v1beta1.ListValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  values_.Clear();
  _internal_metadata_.Clear();
}

bool ListValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.expr.v1beta1.ListValue)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .google.api.expr.v1beta1.Value values = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_values()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.expr.v1beta1.ListValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.expr.v1beta1.ListValue)
  return false;
#undef DO_
}

void ListValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.expr.v1beta1.ListValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .google.api.expr.v1beta1.Value values = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->values_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->values(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.api.expr.v1beta1.ListValue)
}

::google::protobuf::uint8* ListValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.api.expr.v1beta1.ListValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .google.api.expr.v1beta1.Value values = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->values_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->values(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.expr.v1beta1.ListValue)
  return target;
}

size_t ListValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.expr.v1beta1.ListValue)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .google.api.expr.v1beta1.Value values = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->values_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->values(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ListValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.expr.v1beta1.ListValue)
  GOOGLE_DCHECK_NE(&from, this);
  const ListValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ListValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.expr.v1beta1.ListValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.expr.v1beta1.ListValue)
    MergeFrom(*source);
  }
}

void ListValue::MergeFrom(const ListValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.expr.v1beta1.ListValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  values_.MergeFrom(from.values_);
}

void ListValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.expr.v1beta1.ListValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListValue::CopyFrom(const ListValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.expr.v1beta1.ListValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ListValue::IsInitialized() const {
  return true;
}

void ListValue::Swap(ListValue* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ListValue* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void ListValue::UnsafeArenaSwap(ListValue* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ListValue::InternalSwap(ListValue* other) {
  using std::swap;
  CastToBase(&values_)->InternalSwap(CastToBase(&other->values_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ListValue::GetMetadata() const {
  protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MapValue_Entry::InitAsDefaultInstance() {
  ::google::api::expr::v1beta1::_MapValue_Entry_default_instance_._instance.get_mutable()->key_ = const_cast< ::google::api::expr::v1beta1::Value*>(
      ::google::api::expr::v1beta1::Value::internal_default_instance());
  ::google::api::expr::v1beta1::_MapValue_Entry_default_instance_._instance.get_mutable()->value_ = const_cast< ::google::api::expr::v1beta1::Value*>(
      ::google::api::expr::v1beta1::Value::internal_default_instance());
}
void MapValue_Entry::unsafe_arena_set_allocated_key(
    ::google::api::expr::v1beta1::Value* key) {
  if (GetArenaNoVirtual() == NULL) {
    delete key_;
  }
  key_ = key;
  if (key) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.expr.v1beta1.MapValue.Entry.key)
}
void MapValue_Entry::unsafe_arena_set_allocated_value(
    ::google::api::expr::v1beta1::Value* value) {
  if (GetArenaNoVirtual() == NULL) {
    delete value_;
  }
  value_ = value;
  if (value) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:google.api.expr.v1beta1.MapValue.Entry.value)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapValue_Entry::kKeyFieldNumber;
const int MapValue_Entry::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapValue_Entry::MapValue_Entry()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.expr.v1beta1.MapValue.Entry)
}
MapValue_Entry::MapValue_Entry(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.api.expr.v1beta1.MapValue.Entry)
}
MapValue_Entry::MapValue_Entry(const MapValue_Entry& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_key()) {
    key_ = new ::google::api::expr::v1beta1::Value(*from.key_);
  } else {
    key_ = NULL;
  }
  if (from.has_value()) {
    value_ = new ::google::api::expr::v1beta1::Value(*from.value_);
  } else {
    value_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:google.api.expr.v1beta1.MapValue.Entry)
}

void MapValue_Entry::SharedCtor() {
  ::memset(&key_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&key_)) + sizeof(value_));
}

MapValue_Entry::~MapValue_Entry() {
  // @@protoc_insertion_point(destructor:google.api.expr.v1beta1.MapValue.Entry)
  SharedDtor();
}

void MapValue_Entry::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
  if (this != internal_default_instance()) delete key_;
  if (this != internal_default_instance()) delete value_;
}

void MapValue_Entry::ArenaDtor(void* object) {
  MapValue_Entry* _this = reinterpret_cast< MapValue_Entry* >(object);
  (void)_this;
}
void MapValue_Entry::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void MapValue_Entry::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MapValue_Entry::descriptor() {
  ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MapValue_Entry& MapValue_Entry::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  return *internal_default_instance();
}


void MapValue_Entry::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.expr.v1beta1.MapValue.Entry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && key_ != NULL) {
    delete key_;
  }
  key_ = NULL;
  if (GetArenaNoVirtual() == NULL && value_ != NULL) {
    delete value_;
  }
  value_ = NULL;
  _internal_metadata_.Clear();
}

bool MapValue_Entry::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.expr.v1beta1.MapValue.Entry)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .google.api.expr.v1beta1.Value key = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_key()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.api.expr.v1beta1.Value value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_value()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.expr.v1beta1.MapValue.Entry)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.expr.v1beta1.MapValue.Entry)
  return false;
#undef DO_
}

void MapValue_Entry::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.expr.v1beta1.MapValue.Entry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.api.expr.v1beta1.Value key = 1;
  if (this->has_key()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_key(), output);
  }

  // .google.api.expr.v1beta1.Value value = 2;
  if (this->has_value()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.api.expr.v1beta1.MapValue.Entry)
}

::google::protobuf::uint8* MapValue_Entry::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.api.expr.v1beta1.MapValue.Entry)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.api.expr.v1beta1.Value key = 1;
  if (this->has_key()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_key(), deterministic, target);
  }

  // .google.api.expr.v1beta1.Value value = 2;
  if (this->has_value()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_value(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.expr.v1beta1.MapValue.Entry)
  return target;
}

size_t MapValue_Entry::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.expr.v1beta1.MapValue.Entry)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .google.api.expr.v1beta1.Value key = 1;
  if (this->has_key()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *key_);
  }

  // .google.api.expr.v1beta1.Value value = 2;
  if (this->has_value()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *value_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MapValue_Entry::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.expr.v1beta1.MapValue.Entry)
  GOOGLE_DCHECK_NE(&from, this);
  const MapValue_Entry* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MapValue_Entry>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.expr.v1beta1.MapValue.Entry)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.expr.v1beta1.MapValue.Entry)
    MergeFrom(*source);
  }
}

void MapValue_Entry::MergeFrom(const MapValue_Entry& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.expr.v1beta1.MapValue.Entry)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_key()) {
    mutable_key()->::google::api::expr::v1beta1::Value::MergeFrom(from.key());
  }
  if (from.has_value()) {
    mutable_value()->::google::api::expr::v1beta1::Value::MergeFrom(from.value());
  }
}

void MapValue_Entry::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.expr.v1beta1.MapValue.Entry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapValue_Entry::CopyFrom(const MapValue_Entry& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.expr.v1beta1.MapValue.Entry)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapValue_Entry::IsInitialized() const {
  return true;
}

void MapValue_Entry::Swap(MapValue_Entry* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    MapValue_Entry* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void MapValue_Entry::UnsafeArenaSwap(MapValue_Entry* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void MapValue_Entry::InternalSwap(MapValue_Entry* other) {
  using std::swap;
  swap(key_, other->key_);
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MapValue_Entry::GetMetadata() const {
  protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void MapValue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MapValue::kEntriesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MapValue::MapValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.api.expr.v1beta1.MapValue)
}
MapValue::MapValue(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  entries_(arena) {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:google.api.expr.v1beta1.MapValue)
}
MapValue::MapValue(const MapValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      entries_(from.entries_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:google.api.expr.v1beta1.MapValue)
}

void MapValue::SharedCtor() {
}

MapValue::~MapValue() {
  // @@protoc_insertion_point(destructor:google.api.expr.v1beta1.MapValue)
  SharedDtor();
}

void MapValue::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
}

void MapValue::ArenaDtor(void* object) {
  MapValue* _this = reinterpret_cast< MapValue* >(object);
  (void)_this;
}
void MapValue::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void MapValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* MapValue::descriptor() {
  ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MapValue& MapValue::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::scc_info_ListValue.base);
  return *internal_default_instance();
}


void MapValue::Clear() {
// @@protoc_insertion_point(message_clear_start:google.api.expr.v1beta1.MapValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  entries_.Clear();
  _internal_metadata_.Clear();
}

bool MapValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.api.expr.v1beta1.MapValue)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .google.api.expr.v1beta1.MapValue.Entry entries = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_entries()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.api.expr.v1beta1.MapValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.api.expr.v1beta1.MapValue)
  return false;
#undef DO_
}

void MapValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.api.expr.v1beta1.MapValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .google.api.expr.v1beta1.MapValue.Entry entries = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->entries_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->entries(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.api.expr.v1beta1.MapValue)
}

::google::protobuf::uint8* MapValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.api.expr.v1beta1.MapValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .google.api.expr.v1beta1.MapValue.Entry entries = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->entries_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->entries(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.api.expr.v1beta1.MapValue)
  return target;
}

size_t MapValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.api.expr.v1beta1.MapValue)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .google.api.expr.v1beta1.MapValue.Entry entries = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->entries_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->entries(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MapValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.api.expr.v1beta1.MapValue)
  GOOGLE_DCHECK_NE(&from, this);
  const MapValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MapValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.api.expr.v1beta1.MapValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.api.expr.v1beta1.MapValue)
    MergeFrom(*source);
  }
}

void MapValue::MergeFrom(const MapValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.api.expr.v1beta1.MapValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  entries_.MergeFrom(from.entries_);
}

void MapValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.api.expr.v1beta1.MapValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MapValue::CopyFrom(const MapValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.api.expr.v1beta1.MapValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MapValue::IsInitialized() const {
  return true;
}

void MapValue::Swap(MapValue* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    MapValue* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void MapValue::UnsafeArenaSwap(MapValue* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void MapValue::InternalSwap(MapValue* other) {
  using std::swap;
  CastToBase(&entries_)->InternalSwap(CastToBase(&other->entries_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata MapValue::GetMetadata() const {
  protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fapi_2fexpr_2fv1beta1_2fvalue_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1beta1
}  // namespace expr
}  // namespace api
}  // namespace google
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::api::expr::v1beta1::Value* Arena::CreateMaybeMessage< ::google::api::expr::v1beta1::Value >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::expr::v1beta1::Value >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::api::expr::v1beta1::EnumValue* Arena::CreateMaybeMessage< ::google::api::expr::v1beta1::EnumValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::expr::v1beta1::EnumValue >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::api::expr::v1beta1::ListValue* Arena::CreateMaybeMessage< ::google::api::expr::v1beta1::ListValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::expr::v1beta1::ListValue >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::api::expr::v1beta1::MapValue_Entry* Arena::CreateMaybeMessage< ::google::api::expr::v1beta1::MapValue_Entry >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::expr::v1beta1::MapValue_Entry >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::api::expr::v1beta1::MapValue* Arena::CreateMaybeMessage< ::google::api::expr::v1beta1::MapValue >(Arena* arena) {
  return Arena::CreateMessageInternal< ::google::api::expr::v1beta1::MapValue >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
