name: khan-deploy
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: |
            PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
            curl -u ${{ secrets.CIRCLE_TOKEN }}: -X  POST \
               -H 'Content-Type: application/json' \
               -H 'Accept: application/json' \
               -d "{\"branch\":\"${{github.ref}}\", \
                    \"parameters\": { \
                       \"deploy_testnet\": true , \
                       \"pr_number\": \" ${{ github.event.issue.number }} \"
                       } \
                   }" \
               https://circleci.com/api/v2/project/gh/agrebin/taraxa-node/pipeline
        if: steps.check.outputs.triggered == 'true'
