name: prnet-actions
on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"             
      - uses: ./.github/actions/prnet
        id: trigger
        with:
          action: 'cleanup_prnet'
          circleci_slug: 'gh/Taraxa/taraxa-node'
          circle_token: '${{ secrets.CIRCLE_TOKEN }}'
          pull_request: '${{ github.event.number }}' 

