name: trigger-ci-on-branch
 Controls when the action will run.
 Triggers the workflow on push events but only for the some specific branch
on:
  push:
    branches: 
     - testnet

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger CircleCI build
      env:
        CIRCLE_BRANCH: ${{ github.ref }}
        TOKEN: ${{ secrets.CIRCLE_TOKEN }}
      run: |
        curl -X POST \
          -u ${TOKEN}: \
          -H 'Content-Type: application/json' \
          -H 'Accept: application/json' \
          -d "{\"branch\":\"${CIRCLE_BRANCH}\"}" \
          https://circleci.com/api/v2/project/gh/Taraxa-project/taraxa-node/pipeline
