name: trigger-circleci
 Controls when the action will run. Triggers the workflow on push or pull request
 events but only for the master branch
on:
  push:
    branches: 
     - master

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
    - name: Tickle CircleCI
      env:
        CIRCLE_BRANCH: ${{ github.head_ref }}
        PR: ${{ github.ref }}
        TOKEN: ${{ secrets.CIRCLE_TOKEN }}
      run: |
        curl -X POST \
        -u ${TOKEN}: \
        -H 'Content-Type: application/json' \
        -H 'Accept: application/json' \
        -d "{\"branch\":\"${CIRCLE_BRANCH}\",\"pull_request\":\"${PR}\"}" \
        https://circleci.com/api/v2/project/gh/Taraxa-project/taraxa-node/pipeline
