{{ if .Values.bootnode.enabled }}
{{- if .Values.bootnode.serviceMonitor.enabled  }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name:  {{ include "taraxa-boot-node.fullname" . }}
  labels:
    name: boot-node
    app.kubernetes.io/name: boot-node
    helm.sh/chart: {{ include "taraxa-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: boot-node
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
  endpoints:
    - honorLabels: true
      path: /metrics
      port: metrics
{{- if .Values.bootnode.serviceMonitor.metricRelabelings.node }}
      metricRelabelings:
{{- .Values.bootnode.serviceMonitor.metricRelabelings.node | toYaml | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}
