{{ if .Values.bootnode.enabled }}
{{ if .Values.bootnode.loadBalancer.enabled }}
{{- range $key, $value := .Values.bootnode.loadBalancer.addresses }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-boot-node-udp-{{ $key }}
  {{- with $.Values.bootnode.loadBalancer.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    name: {{ $.Release.Name }}-boot-node-udp-{{ $key }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ $value | quote }}
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-boot-node-{{ $key }}
  ports:
    - name: udp-listen-port
      port: 10002
      targetPort: 10002
      protocol: UDP
{{- end }}
{{- end }}
{{- end }}
