{{ if .Values.consensusnode.enabled }}

{{- if .Values.consensusnode.service.ports  }}
# Note: This is a headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taraxa-consensus-node.fullname" . }}
  labels:
    name: consensus-node
    app.kubernetes.io/name: consensus-node
    helm.sh/chart: {{ include "taraxa-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: consensus-node
    app.kubernetes.io/name: {{ .Release.Name }}-consensus-node
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- range $port := .Values.consensusnode.service.ports }}
    - name: {{ $port.name | default $port.port }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort | default $port.port }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
  {{- end }}
{{- end }}

{{ if .Values.consensusnode.nodePort.enabled }}
{{- range $key, $value := .Values.consensusnode.nodePort.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-taraxa-consensusnode-discovery-{{ $key }}
  labels:
    name: {{ $.Release.Name }}-taraxa-consensusnode-discovery-{{ $key }}
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-consensus-node-{{ $key }}
  ports:
    - name: udp-listen-port
      port: {{ $value }}
      targetPort: {{ $value }}
      nodePort: {{ $value }}
      protocol: UDP
    - name: tcp-listen-port
      port: {{ $value }}
      targetPort: {{ $value }}
      nodePort: {{ $value }}
      protocol: TCP
{{- end }}
{{- end }}

{{- end }}
