apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ include "taraxa-node.fullname" . }}-manager"
  labels:
    app: manager
    app.kubernetes.io/name: {{ include "taraxa-node.name" . }}
    helm.sh/chart: {{ include "taraxa-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  serviceName: "{{ include "taraxa-node.fullname" . }}-manager"
  selector:
    matchLabels:
      app: manager
      app.kubernetes.io/name: {{ include "taraxa-node.name" . }}
      helm.sh/chart: {{ include "taraxa-node.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      release: {{ .Release.Name }}
  template:
    metadata:
      name: "{{ include "taraxa-node.fullname" . }}-manager"
      labels:
        app: manager
        app.kubernetes.io/name: {{ include "taraxa-node.name" . }}
        helm.sh/chart: {{ include "taraxa-node.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: manager
          image: "python:3.8"
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "--"]
          args: [ "python3 /usr/local/bin/manager.py" ]
          volumeMounts:
            - name: script
              mountPath: /usr/local/bin/manager.py
              readOnly: true
              subPath: manager.py
      volumes:
        - name: script
          configMap:
            defaultMode: 0700
            name: "{{ include "taraxa-node.fullname" . }}-manager"
