{{ if .Values.node.enabled }}
# Note: This is a headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taraxa-node.fullname" . }}
  labels:
    name: taraxa-node
    app.kubernetes.io/name: taraxa-node
    helm.sh/chart: {{ include "taraxa-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: taraxa-node
    app.kubernetes.io/name: {{ include "taraxa-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- range $port := .Values.node.service.ports }}
    - name: {{ $port.name | default $port.port }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort | default $port.port }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "taraxa-node.fullname" . }}-head
  labels:
    app.kubernetes.io/name: taraxa-node-head
    helm.sh/chart: {{ include "taraxa-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: taraxa-node
    app.kubernetes.io/name: {{ include "taraxa-node.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- range $port := .Values.node.service.ports }}
    - name: {{ $port.name | default $port.port }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort | default $port.port }}
      {{- if $port.protocol }}
      protocol: {{ $port.protocol }}
      {{- end }}
  {{- end }}
{{- end }}

{{ if .Values.node.enabled }}
{{ if .Values.node.loadBalancer.enabled }}
{{- range $key, $value := .Values.node.loadBalancer.addresses }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-taraxa-node-udp-{{ $key }}
  labels:
    name: {{ $.Release.Name }}-taraxa-node-udp-{{ $key }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ $value | quote }}
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-taraxa-node-{{ $key }}
  ports:
    - name: udp-listen-port
      port: 10002
      targetPort: 10002
      protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-taraxa-node-tcp-{{ $key }}
  labels:
    name: {{ $.Release.Name }}-taraxa-node-tcp-{{ $key }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ $value | quote }}
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-taraxa-node-{{ $key }}
  ports:
    - name: tcp-listen-port
      port: 10002
      targetPort: 10002
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}
