apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "taraxa-node.fullname" . }}-service-registry"
  labels:
    app: service-registry
    app.kubernetes.io/name: {{ include "taraxa-node.name" . }}
    helm.sh/chart: {{ include "taraxa-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]