{{ if .Values.snapshotnode.fullnode.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "taraxa-snapshot-fullnode.fullname" . }}
  labels:
    app: snapshot-fullnode
    app.kubernetes.io/name: snapshot-fullnode
    helm.sh/chart: {{ include "taraxa-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  serviceName: {{ include "taraxa-snapshot-fullnode.fullname" . }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: snapshot-fullnode
      partition: a
      app.kubernetes.io/name: {{ .Release.Name }}-snapshot-fullnode
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      name: snapshot-fullnode
      labels:
        app: snapshot-fullnode
        partition: a
        app.kubernetes.io/name: {{ .Release.Name }}-snapshot-fullnode
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        kubernetes.io/change-cause: "Configuration through configmaps."
    spec:
      initContainers:
        {{ if .Values.explorer.enabled }}
        - name: wait-for-explorer
          image: dwdraju/alpine-curl-jq:latest
          command: ["/bin/entrypoint.sh"]
          volumeMounts:
            - name: explorer-check
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
        {{- end }}
        - name: config-adapter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}
          env:
          - name: HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          command: ["/bin/entrypoint.sh"]
          volumeMounts:
            - name: initconfig
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            - name: initconfig
              mountPath: /bin/genconfig.py
              readOnly: true
              subPath: genconfig.py
            - name: {{ .Values.snapshotnode.fullnode.persistence.name }}
              mountPath: /root/.taraxa
      containers:
        {{- if .Values.slack.enabled }}
        - name: status
          image: "python:3.8"
          imagePullPolicy: IfNotPresent
          env:
          - name: SLACK_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}
                key: SLACK_TOKEN
          - name: SLACK_CHANNEL
            value: {{ .Values.slack.channel }}
          - name: K8S_CLUSTER
            value: {{ .Values.slack.k8s_cluster }}
          command: ["/bin/bash", "-c", "--"]
          args: [ "pip install -r /app/requirements.txt && python /app/status.py" ]
          volumeMounts:
            - name: status-requirements
              mountPath: /app/requirements.txt
              readOnly: true
              subPath: requirements.txt
            - name: status-script
              mountPath: /app/status.py
              readOnly: true
              subPath: status.py
        {{- end }}
        - name: snapshots-uploader
          image: "{{ .Values.snapshotter.image.repository }}:{{ .Values.snapshotter.image.tag }}"
          imagePullPolicy: {{ .Values.snapshotter.image.pullPolicy }}
          command: [ "/bin/bash", "-c", "--" ]
          # args: [ "pip install taraxa-node-snapshotter && taraxa-node-snapshotter listen" ]
          args: [ "tail -f /dev/null" ]
          {{- if .Values.snapshotter.env }}
          env:
            {{- toYaml .Values.snapshotter.env | nindent 12 }}
          {{- end }}
          volumeMounts:
          - name: snapshot-repo-config
            mountPath: /etc/pip.conf
            readOnly: true
            subPath: pip.conf
          - name: snapshot-repo-config
            mountPath: /root/.pypirc
            readOnly: true
            subPath: .pypirc
          {{- if .Values.snapshotter.extraVolumeMounts }}
            {{- toYaml .Values.snapshotter.extraVolumeMounts | nindent 10}}
          {{- end }}
          - name: {{ .Values.snapshotnode.fullnode.persistence.name }}
            mountPath: /root/.taraxa
        - name: snapshot-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.snapshotnode.fullnode.args | nindent 12 }}
          env:
            - name: DEBUG
              value: "{{ .Values.snapshotnode.fullnode.debug }}"
            - name: HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if not .Values.snapshotnode.fullnode.probes.enabled }}
            - name: TARAXA_SLEEP_DIAGNOSE
              value: "true"
          {{- end }}
          ports:
            {{- toYaml .Values.snapshotnode.fullnode.ports | nindent 12 }}
          {{- if .Values.snapshotnode.fullnode.probes.enabled }}
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "ps -A | grep taraxad"
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
              - curl
              - -X
              - POST
              - -H
              - "'Content-Type: application/json'"
              - -d
              - "'{\"jsonrpc\":\"2.0\",\"method\":\"taraxa_protocolVersion\",\"params\": [],\"id\":1}'"
              - http://127.0.0.1:7777
            initialDelaySeconds: 10
            periodSeconds: 5
          {{- end }}
          resources:
            {{- toYaml .Values.snapshotnode.fullnode.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.snapshotnode.fullnode.persistence.name }}
              mountPath: /root/.taraxa
          securityContext:
            capabilities:
              add:
              - SYS_PTRACE
      {{- with .Values.snapshotnode.fullnode.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: initconfig
          configMap:
            defaultMode: 0700
            name: {{ .Release.Name }}-snapshot-fullnode-init-script
        {{ if .Values.explorer.enabled }}
        - name: explorer-check
          configMap:
            defaultMode: 0700
            name: {{ include "taraxa-node.fullname" . }}-explorer-check
        {{- end }}
        - name: snapshot-repo-config
          configMap:
            defaultMode: 0700
            name: {{ .Release.Name }}-snapshot-repo-config
        {{- if .Values.slack.enabled }}
        - name: status-requirements
          configMap:
            defaultMode: 0700
            name: {{ .Release.Name }}-node-status-script
        - name: status-script
          configMap:
            defaultMode: 0700
            name: {{ .Release.Name }}-node-status-script
        {{- end }}
        {{- if not .Values.persistence.enabled }}
        - name: {{ .Values.persistence.name }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.snapshotter.extraVolumes }}
          {{- toYaml .Values.snapshotter.extraVolumes | nindent 8}}
        {{- end }}
  {{- if .Values.snapshotnode.fullnode.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.snapshotnode.fullnode.persistence.name }}
    spec:
      accessModes:
        - {{ .Values.snapshotnode.fullnode.persistence.accessMode | quote }}
    {{- if .Values.snapshotnode.fullnode.persistence.storageClass }}
    {{- if (eq "-" .Values.snapshotnode.fullnode.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.snapshotnode.fullnode.persistence.storageClass }}"
    {{- end }}
    {{- end }}
      resources:
        requests:
          storage: "{{ .Values.snapshotnode.fullnode.persistence.size }}"
  {{- end }}
{{- end }}
