{{ if .Values.node.enabled }}
{{ if .Values.node.nodePort.enabled }}
{{- range $key, $value := .Values.node.nodePort.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-taraxa-node-discovery-{{ $key }}
  labels:
    name: {{ $.Release.Name }}-taraxa-node-discovery-{{ $key }}
spec:
  type: NodePort
  selector:
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-taraxa-node-{{ $key }}
  ports:
    - name: udp-listen-port
      port: 10002
      targetPort: 10002
      nodePort: {{ $value }}
      protocol: UDP
    - name: tcp-listen-port
      port: 10002
      targetPort: 10002
      nodePort: {{ $value }}
      protocol: TCP
{{- end }}
{{- end }}
{{- end }}
