{{ if .Values.node.enabled }}
{{ if .Values.node.indexer.enabled }}
{{- if .Values.node.indexer.ingress.enabled -}}

{{- $fullName := include "taraxa-node.fullname" . -}}
{{- $apiIsStable := eq (include "taraxa-node.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "taraxa-node.ingress.supportsPathType" .) "true" -}}
{{- $serviceName := printf "%s-%s" (include "taraxa-node.fullname" .) "head" -}}

{{- $servicePortHttp := 8080 -}}

{{- range .Values.node.service.ports }}
  {{ if eq .name "http-indexer"}} {{ $servicePortHttp = .port }} {{ end }}
{{- end }}

{{- $pathType := .Values.node.ingress.pathType | default "ImplementationSpecific" -}}
---
apiVersion: {{ include "taraxa-node.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}-indexer
  labels:
    app: taraxa-node
    app.kubernetes.io/name: {{ include "taraxa-node.name" . }}
    helm.sh/chart: {{ include "taraxa-node.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.node.indexer.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $apiIsStable }}
{{- if .Values.node.indexer.ingress.ingressClassName }}
  ingressClassName: {{ .Values.node.indexer.ingress.ingressClassName }}
{{- end }}
{{- end }}
  {{- if .Values.wildCertDomainSecret }}
  tls:
    - hosts:
        - {{ include "taraxa-node.indexerName" . | quote }}
      secretName: {{ .Values.wildCertDomainSecret }}
  {{- end }}
  rules:
    - host: {{ include "taraxa-node.indexerName" . | quote }}
      http:
        paths:
          - path: /
            {{- if and $pathType $ingressSupportsPathType }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePortHttp }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePortHttp }}
              {{- end }}
{{- end }}
{{- end }}
{{- end }}
